title: Titterpig Academy
description: Creating Resources to learn TTRPGS
sitename: Titterpig Academy
baseurl: '/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME